/**
 * Whose quest is this — UX-339 (BIND).
 *
 * A Knowledge Mine session in flight writes to **three** propose-and-confirm
 * rails plus three more collections at `endSession`: `hours`, `skillSnapshots`,
 * `xpLedger`, `evaluationSessions`, `days` and `wordProgress`. Every one of
 * those reads `activeChildId` at the moment the session ends, and a running
 * quest survives a change of active child — so a quest Lincoln answered
 * fourteen questions of could be filed, credited, levelled and paid for as
 * London's. It is the highest-value fix of FIX-223's five, and the census filed
 * it as a P1 it could not touch until `CLAUDE.md`'s **Attribution-only fixes
 * are pre-authorised** (owner, 2026-09-10) unblocked it.
 *
 * ── Why BIND, against the census's own table (§3) ─────────────────────────
 *
 * The census prescribed BIND and did not say why; this run had to decide it.
 * BIND is for work that is *unsaved and expensive to recreate*, and a quest in
 * flight is the strongest case of that in the repo: the questions were
 * generated by paid model calls, a child has answered a run of them, an
 * idle-aware timer has been counting real instructional minutes, and — the
 * decider — **rewards are already being written per answer**. `bankAnswerReward`
 * lands a diamond and its XP as each correct answer arrives, so by the time the
 * header moves, part of the session has ALREADY been written under its owner.
 *
 * That rules the other four out rather than merely making BIND nicer:
 *
 * - **RESET** would discard a half-answered quest a child is in the middle of,
 *   after paying for it — and would leave the diamonds already banked for the
 *   owner orphaned against a session recorded for someone else.
 * - **HIDE** (`WorkshopPage`'s answer) works because a Workshop draft is
 *   already persisted on its own child's shelf and nothing is in flight. Here
 *   an idle-aware timer keeps counting and the AI keeps answering behind the
 *   hidden screen — hiding it would hide a running write, not prevent one.
 * - **GATE** answers "the read has not settled"; this read settled long ago.
 * - **SAFE** was never available: the write demonstrably follows the header.
 *
 * So the session's own owner wins — the `CreateSightWordBook` /
 * `useCreativeTimer.ownerChildId` shape, applied to the surface that reaches the
 * most rails at once. **Nothing is discarded**, which is the whole point: a
 * quest costs paid calls and a child's attention.
 *
 * ── The DOC-25 terms ──────────────────────────────────────────────────────
 *
 * **No number changes**: not the 5-minute hours bucket (`Math.ceil(seconds / 60
 * / 5) * 5`), not its `minutes >= 5` floor, not `XP_PER_DIAMOND`, not the flat
 * 15-XP completion bonus, not `hasSufficientCompletion`, not a working-level
 * computation, not a mastery gate. **No stored shape change**: the owner lives
 * in a ref for the life of the session and is written to no document — every
 * payload is byte-identical but for the `childId` it carries. **No record
 * rewritten**: sessions already misfiled are data, and correcting them is a
 * separate proposal.
 *
 * Pure: no React, no Firestore, never throws.
 */

/**
 * The child a quest session belongs to, captured when the session starts.
 *
 * The name rides along so the surface can say whose the quest is without a
 * second lookup — and so it still reads correctly if the family list is
 * refetched mid-session.
 */
export interface QuestSessionOwner {
  childId: string
  childName: string
}

/**
 * The child every write in this session is addressed to.
 *
 * The session's own owner wins. The live child is the fallback for a hook with
 * no session running — which is exactly the behaviour that shipped before, so
 * the intro screen, the resume card and the eligibility reads are unchanged.
 */
export function resolveQuestOwnerChildId(
  owner: QuestSessionOwner | null | undefined,
  liveChildId: string,
): string {
  return owner?.childId || liveChildId
}

/** True when the header has moved off the child this quest belongs to. */
export function questLeftItsChild(
  owner: QuestSessionOwner | null | undefined,
  liveChildId: string,
): boolean {
  if (!owner?.childId || !liveChildId) return false
  return owner.childId !== liveChildId
}

/**
 * What the quest screen says once the header is on someone else — named, and
 * **before** the last question, not in a receipt afterwards (the UX-313 rule).
 *
 * Kid copy: this is a kid's screen, so it is held to the shared readability bar
 * (`src/test/kidReadability.ts`) — short sentences, nothing over two syllables.
 * The parent is the one who moved the header, but the boy is the one looking at
 * it, and a sentence he cannot read is a sentence that is not there.
 */
export function questOwnerLines(ownerName: string): string[] {
  return [`This quest is ${ownerName}'s.`, `It will be saved for ${ownerName}.`]
}
