import { describe, expect, it } from "vitest";
import {
  FOUNDATION_SUMMARY_MAP,
  FOUNDATION_SUMMARY_NODES,
  FOUNDATIONS_GRAPH_VERSION,
  summaryNodesForDomain,
} from "./foundationsGraphSummary.js";
import {
  allFoundationNodes,
  foundationGraphs,
  foundationGraphVersion,
} from "../../shared/foundations/graph.js";

/**
 * Pins the server-side graph summary: the invariants that matter for synthesis —
 * unique ids, in-graph edges, plain-language names, both domains present — and,
 * since UX-296, that it is a PROJECTION of the one shared spine rather than a
 * copy of it.
 *
 * It used to be a machine-generated mirror regenerated by hand
 * (`scripts/genFoundationsSummary.ts`, now retired),
 * and this suite could only check the mirror against itself: it could not cross
 * the client/functions build boundary, so a
 * re-curation that forgot the generator could pass every assertion here while
 * Cloud Functions named stale concepts. The spine is now one
 * definition both projects compile, so the comparison below is finally possible.
 */
describe("foundationsGraphSummary", () => {
  it("has the expected shape and version tag", () => {
    expect(FOUNDATION_SUMMARY_NODES.length).toBe(60);
    expect(FOUNDATIONS_GRAPH_VERSION).toMatch(/^reading@\d+\+math@\d+$/);
  });

  it("has unique ids and both domains", () => {
    const ids = FOUNDATION_SUMMARY_NODES.map((n) => n.id);
    expect(new Set(ids).size).toBe(ids.length);
    expect(summaryNodesForDomain("reading").length).toBeGreaterThan(0);
    expect(summaryNodesForDomain("math").length).toBeGreaterThan(0);
    expect(
      summaryNodesForDomain("reading").length + summaryNodesForDomain("math").length,
    ).toBe(FOUNDATION_SUMMARY_NODES.length);
  });

  it("keeps every `underlies` edge in-graph and in-domain", () => {
    for (const n of FOUNDATION_SUMMARY_NODES) {
      for (const child of n.underlies) {
        const target = FOUNDATION_SUMMARY_MAP[child];
        expect(target, `${n.id} → ${child} must exist`).toBeDefined();
        expect(target.domain).toBe(n.domain);
      }
    }
  });

  it("carries a plain-language kidName + description per node (no band numbers)", () => {
    for (const n of FOUNDATION_SUMMARY_NODES) {
      expect(n.kidName.trim()).toBeTruthy();
      expect(n.parentDescription.trim()).toBeTruthy();
      expect(n.kidName).not.toMatch(/band\s*\d/i);
      expect(n.kidName).not.toMatch(/level\s*\d/i);
    }
  });
});

/**
 * UX-296's guard: the summary is DERIVED from `functions/src/shared/foundations/`,
 * and the projection is the six fields the server reads, in spine order.
 *
 * Drift controls:
 * - write `FOUNDATION_SUMMARY_NODES` back out as a literal array (the pre-UX-296
 *   shape) and change one `kidName`, band or edge in it — "every node, field for
 *   field" fails, naming the node. That is the drift this row was filed for, and
 *   nothing caught it before.
 * - drop a field from the projection, or add one that is not in `ConceptNode` —
 *   the same assertion fails.
 * - reorder only the projection (e.g. `.sort()`) — "in spine order" fails.
 * - hand-write the version tag as a literal again — "names the graph versions"
 *   fails the moment either graph's version moves.
 *
 * A curation of the shared graph itself moves BOTH sides together and passes
 * here, which is the point: the graph tests
 * (`src/core/foundations/graphIntegrity.test.ts`, `foundations.test.ts`) hold a
 * re-curation to its node counts, bands and edges; `graphSource.test.ts` pins the
 * shared domain order separately.
 */
describe("foundationsGraphSummary is derived from the shared spine", () => {
  it("names the graph versions the spine declares", () => {
    expect(FOUNDATIONS_GRAPH_VERSION).toBe(foundationGraphVersion());
    expect(FOUNDATIONS_GRAPH_VERSION).toBe(
      `reading@${foundationGraphs[0].version}+math@${foundationGraphs[1].version}`,
    );
  });

  it("carries every node of both graphs, field for field, in spine order", () => {
    expect(FOUNDATION_SUMMARY_NODES).toEqual(
      allFoundationNodes.map((n) => ({
        id: n.id,
        domain: n.domain,
        band: n.band,
        kidName: n.kidName,
        parentDescription: n.parentDescription,
        underlies: n.underlies,
      })),
    );
    expect(FOUNDATION_SUMMARY_NODES.map((n) => n.id)).toEqual(
      allFoundationNodes.map((n) => n.id),
    );
  });

  it("copies rather than aliases, so the server cannot reach the canonical graph", () => {
    for (const [i, n] of FOUNDATION_SUMMARY_NODES.entries()) {
      expect(n).not.toBe(allFoundationNodes[i]);
      expect(n.underlies).not.toBe(allFoundationNodes[i].underlies);
    }
  });

  it("splits by domain the same way the graphs do", () => {
    for (const graph of foundationGraphs) {
      expect(summaryNodesForDomain(graph.domain).map((n) => n.id)).toEqual(
        graph.nodes.map((n) => n.id),
      );
    }
  });
});
