/**
 * Crops a single armor piece from the 3×2 sheet image generated by generateArmorSheet.
 *
 * Piece order (0-indexed), matching ARMOR_PIECE_SHEET_INDEX:
 *   0 = belt_of_truth        (col 0, row 0)
 *   1 = breastplate           (col 1, row 0)
 *   2 = shoes_of_peace        (col 2, row 0)
 *   3 = shield_of_faith       (col 0, row 1)
 *   4 = helmet_of_salvation   (col 1, row 1)
 *   5 = sword_of_the_spirit   (col 2, row 1)
 */
export async function cropArmorPiece(
  sheetUrl: string,
  pieceIndex: number,   // 0–5
  outputSize: number = 256,
): Promise<string> {
  const img = new Image()
  img.crossOrigin = 'anonymous'
  await new Promise<void>((res, rej) => {
    img.onload = () => res()
    img.onerror = rej
    img.src = sheetUrl
  })

  // Each cell in a 3×2 grid on a 1024×1024 image
  const cols = 3
  const rows = 2
  const cellW = img.naturalWidth / cols   // ~341px
  const cellH = img.naturalHeight / rows  // ~512px

  const col = pieceIndex % cols
  const row = Math.floor(pieceIndex / cols)

  const canvas = document.createElement('canvas')
  canvas.width = outputSize
  canvas.height = outputSize
  const ctx = canvas.getContext('2d')!

  ctx.drawImage(
    img,
    col * cellW, row * cellH,   // source x, y
    cellW, cellH,                // source width, height
    0, 0,                        // dest x, y
    outputSize, outputSize,      // dest width, height
  )

  return canvas.toDataURL('image/png')
}
