/**
 * The foundations spine, assembled — one definition for both projects (UX-296).
 *
 * `foundationGraphs`, `allFoundationNodes`, `FOUNDATION_NODE_MAP`,
 * `foundationGraphVersion` and `foundationNodesForDomain` are pure derivations of
 * the two curated graphs. They moved here unchanged from
 * `src/core/foundations/index.ts`, which keeps its path and re-exports them, so
 * every app consumer is untouched.
 *
 * Why here and not on the app side: the Cloud Functions build could not import
 * the client module, so `functions/src/ai/data/foundationsGraphSummary.ts` was a
 * hand-committed MIRROR of these nodes, regenerated by a script somebody had to
 * remember to run. That summary is now a projection of THESE arrays, computed at
 * module load, so a re-curation reaches the server by the compiler rather than by
 * a manual step. It is the `functions/src/shared/` rule: editing the spine without
 * updating a reader fails to COMPILE, on whichever side broke (ARCH-47).
 *
 * Pure data and pure derivations: no seeding, no state logic, nothing
 * environment-specific. The bootstrap seeder stays on the app side.
 */

import type { ConceptGraph, ConceptNode, FoundationDomain } from './types.js'
import { readingGraph } from './readingGraph.js'
import { mathGraph } from './mathGraph.js'

/** Both domain graphs, in spine order (reading, then math). */
export const foundationGraphs: ConceptGraph[] = [readingGraph, mathGraph]

/** Every foundation node across both domains, flattened. */
export const allFoundationNodes: ConceptNode[] = foundationGraphs.flatMap(
  (g) => g.nodes,
)

/** Flat lookup of foundation nodes by id (both domains). */
export const FOUNDATION_NODE_MAP: Record<string, ConceptNode> = Object.fromEntries(
  allFoundationNodes.map((n) => [n.id, n]),
)

/**
 * A single combined version tag for "which spine this model was synthesized
 * against" (stored on `LearnerModel.graphVersion`). Both domain graphs move
 * together, so the tag names both.
 */
export function foundationGraphVersion(): string {
  return `reading@${readingGraph.version}+math@${mathGraph.version}`
}

/** The nodes for one domain. */
export function foundationNodesForDomain(domain: FoundationDomain): ConceptNode[] {
  return foundationGraphs.find((g) => g.domain === domain)?.nodes ?? []
}
