// ── Apply: the one lane that writes a planned week (FEAT-150) ────────────────
//
// For three years "Apply" lived inside `PlannerChatPage` — ~230 lines in the
// middle of a 3,400-line component, reachable only by rendering the planner and
// tapping its bar. That was fine while the planner was the only thing that could
// apply a week. It stopped being fine the moment the chat needed to do the same
// thing, because the alternative to extracting it is writing it a second time,
// and the two audited compliance failures in this app's history (FEAT-111,
// FEAT-114's P0) were both *a second copy of a day-write that forgot a rule*.
//
// So this module is the extraction the architecture audit named, and the rule it
// exists to hold is one sentence: **there is one Apply, and every caller uses
// it.** The planner calls it. The chat calls it (through
// `shelly-chat/writeNextWeekDraft.ts`, which adds the next-week-only rail its
// own lane needs). Neither reimplements a line of it.
//
// ── What is here, and what deliberately is not ───────────────────────────────
// Here: the two writes that ARE applying a week — the `WeekPlan` upsert (the
// child's goals for that week) and the per-day `checklist`/`blocks`/budget
// write, including the FEAT-111 retain rules and the FEAT-114 guarded writer.
//
// Not here, and staying on the planner page: lesson-card generation, the
// read-aloud `plannerDefaults` write, help-card batch generation, the chapter
// question pool, the conversation persist, and every snack and chat message.
// Those are the *planner's* enrichments around an apply, not the apply — they
// are AI spends and page state, and a chat that ran them would be spending the
// parent's money on a tap she was told writes a week. The one that crosses the
// seam is the lesson-card map, which the planner builds BEFORE the write and
// hands in; the chat hands in nothing and its items simply carry no
// `lessonCardId`, exactly as an item with no generated card always has.
//
// ── plannedMinutes ───────────────────────────────────────────────────────────
// Blocks written here carry `plannedMinutes`. That has always been Apply's
// sanctioned lane — a planned week IS a claim about hours — and it is the reason
// the no-`plannedMinutes` rail stands everywhere else in the chat's write
// surface (FEAT-142's live-day add writes a checklist row and no block at all).
// Through this module the chat inherits the lane legitimately, because it is the
// same lane, not a copy of it.

import { doc, getDoc, setDoc } from 'firebase/firestore'

import {
  daysCollection,
  weeksCollection,
} from '../../core/firebase/firestore'
import type {
  ChecklistItem,
  DayBlock,
  DayLog,
  DraftDayPlan,
  DraftWeeklyPlan,
} from '../../core/types'
import { DayBlockType, SubjectBucket } from '../../core/types/enums'
import {
  findWorkbookConfigId,
  type WorkbookConfigLike,
} from '../../core/utils/workbookMatching'
import { retainBlocksForApply, retainChecklistForApply } from '../today/applyReset'
import { dayLogDocId } from '../today/daylog.model'
import { setDayLogGuarded } from '../today/dayWriteGuard'
import {
  buildShiftedWeekPlan,
  dateKeyForDayPlan,
  WEEK_DAYS,
  type WeekDay,
} from './chatPlanner.logic'

/**
 * The slice of an `ActivityConfig` the FEAT-62 workbook join needs.
 *
 * Deliberately the matcher's OWN type rather than a second declaration of the
 * same shape: two structurally-identical interfaces are two things that can
 * drift, and the one thing this module must not do is disagree with
 * `findWorkbookConfigId` about what a workbook config looks like.
 */
export type ApplyWorkbookConfig = WorkbookConfigLike

export interface ApplyWeekPlanInput {
  familyId: string
  childId: string
  /** Sunday-start key of the week being written (`weekRange.start`'s shape). */
  weekStart: string
  draft: DraftWeeklyPlan
  /** Every child in the family — needed to seed an absent `WeekPlan` doc. */
  children: { id: string }[]
  /** The family's live activity configs, for the FEAT-62 `workbookConfigId` join. */
  activityConfigs: ApplyWorkbookConfig[]
  /**
   * `item.title → lessonCardId`, generated by the caller BEFORE the write. The
   * planner passes its map; the chat passes none, and its items carry no
   * `lessonCardId` — the same shape an item whose card generation failed has
   * always had.
   */
  lessonCardMap?: Map<string, string>
  /**
   * The week's read-aloud book, as a three-state field:
   *   - `undefined` — **leave the week's existing value alone.** What the chat
   *     passes: it has no book picker, and silently clearing a book the parent
   *     chose in the planner would be a write she never asked for.
   *   - a string — set it.
   *   - `null` — clear it. What the planner passes when its picker is empty,
   *     preserving the page's long-standing "deselecting clears it" behaviour.
   */
  readAloudBookId?: string | null
  /**
   * Whether the acting profile may write a week. **Required**, never inferred
   * from the route: `/chat` sits outside `RequireParent`, and the lesson of
   * FEAT-133 is that a gate stated only at the component is a gate one new call
   * site away from being absent.
   */
  canEdit: boolean
}

export interface ApplyWeekPlanResult {
  /** Date keys actually written, in write order. */
  daysWritten: string[]
  /** Whether the `WeekPlan` doc was upserted (false only when nothing applied). */
  weekPlanWritten: boolean
}

/**
 * Thrown when a week apply fails partway through.
 *
 * The FEAT-138 honesty rule, applied to a week: a day write that fails after
 * earlier days already landed leaves the week **half-written**, and the app must
 * say which half rather than roll back blind. Rolling back is not available to
 * us in any honest form — the earlier writes went through the preservation
 * guard and may already have merged with completed work — so the error carries
 * what DID land and the caller states it.
 */
export class WeekApplyError extends Error {
  readonly daysWritten: string[]
  readonly weekPlanWritten: boolean
  constructor(
    message: string,
    partial: ApplyWeekPlanResult,
    options?: { cause?: unknown },
  ) {
    super(message, options)
    this.name = 'WeekApplyError'
    this.daysWritten = partial.daysWritten
    this.weekPlanWritten = partial.weekPlanWritten
  }
}

/** The `DayBlock` type a draft item's subject maps onto. */
export function subjectToDayBlockType(subject: SubjectBucket): DayBlockType {
  switch (subject) {
    case SubjectBucket.Reading: return DayBlockType.Reading
    case SubjectBucket.Math: return DayBlockType.Math
    case SubjectBucket.LanguageArts: return DayBlockType.Reading
    case SubjectBucket.Science: return DayBlockType.Project
    case SubjectBucket.SocialStudies: return DayBlockType.Together
    default: return DayBlockType.Other
  }
}

/**
 * The checklist rows one draft day becomes. Pure.
 *
 * The `(Nm)` label suffix is load-bearing across the app, not decoration:
 * `manualDayItem` and `watchDayItem` both build their labels to match it byte
 * for byte so a row added by hand and a row added by Apply are the same shape.
 *
 * The FEAT-62 `workbookConfigId` stamp happens HERE because this is the only
 * point at which the item's workbook identity is still recoverable — the
 * routine→item pipeline round-trips through free text and drops the config id.
 */
export function buildApplyChecklist(
  items: DraftDayPlan['items'],
  activityConfigs: ApplyWorkbookConfig[],
  lessonCardMap: Map<string, string>,
): ChecklistItem[] {
  return items.map((item) => {
    const workbookConfigId = findWorkbookConfigId(
      { label: item.title, subjectBucket: item.subjectBucket },
      activityConfigs,
    )
    return {
      label: `${item.title} (${item.estimatedMinutes}m)`,
      completed: false,
      skillTags: item.skillTags,
      ladderRef: item.ladderRef,
      source: 'planner' as const,
      mvdEssential: item.mvdEssential ?? item.category === 'must-do',
      category: item.category ?? 'must-do',
      estimatedMinutes: item.estimatedMinutes,
      subjectBucket: item.subjectBucket,
      ...(lessonCardMap.get(item.title) ? { lessonCardId: lessonCardMap.get(item.title) } : {}),
      ...(item.skipGuidance ? { skipGuidance: item.skipGuidance } : {}),
      ...(item.itemType ? { itemType: item.itemType } : {}),
      ...(item.evaluationMode ? { evaluationMode: item.evaluationMode } : {}),
      ...(item.link ? { link: item.link } : {}),
      ...(item.bookId ? { bookId: item.bookId } : {}),
      ...(item.watchVideoId ? { watchVideoId: item.watchVideoId } : {}),
      ...(workbookConfigId ? { workbookConfigId } : {}),
    }
  })
}

/**
 * The time blocks one draft day becomes. Pure.
 *
 * App blocks are deliberately excluded: they are screen-time containers, not
 * instructional time, and giving them `plannedMinutes` would put them in the
 * hours math.
 */
export function buildApplyBlocks(items: DraftDayPlan['items']): DayBlock[] {
  return items
    .filter((item) => !item.isAppBlock)
    .map((item) => ({
      type: subjectToDayBlockType(item.subjectBucket),
      title: item.title,
      subjectBucket: item.subjectBucket,
      plannedMinutes: item.estimatedMinutes,
      skillTags: item.skillTags,
      ladderRef: item.ladderRef,
      source: 'planner' as const,
    }))
}

/**
 * The document Apply writes over an EXISTING day. Pure — the retain rules and
 * the append, with nothing read or written.
 *
 * The applied plan is authoritative for the days it covers (owner decision
 * 2026-07-19), but authority stops at three things it may never take
 * (`applyReset.ts`, HARD CONSTRAINT): completed work and its minutes/evidence,
 * manually-added rows, and any block carrying logged `actualMinutes`. Those are
 * retained and the fresh plan is appended after them.
 */
export function buildAppliedDayLog(
  existing: DayLog,
  checklist: ChecklistItem[],
  blocks: DayBlock[],
  dailyBudgetMinutes: number,
  now: string,
): DayLog {
  return {
    ...existing,
    checklist: [...retainChecklistForApply(existing.checklist ?? []), ...checklist],
    blocks: [...retainBlocksForApply(existing.blocks ?? []), ...blocks],
    dailyBudgetMinutes,
    updatedAt: now,
  }
}

/** The days of a draft that Apply will actually write, in order. */
export function applicableDays(draft: DraftWeeklyPlan): DraftDayPlan[] {
  return draft.days.filter(
    (d) =>
      d.items.some((item) => item.accepted) &&
      WEEK_DAYS.includes(d.day as WeekDay),
  )
}

/** The week's goals, as the `WeekPlan` records them. */
export function planGoalsForDraft(draft: DraftWeeklyPlan): string[] {
  return draft.days
    .flatMap((d) => d.items)
    .filter((item) => item.accepted && !item.isAppBlock)
    .map((item) => item.title)
}

/**
 * Upsert the `WeekPlan` doc's `childGoals` for the applying child.
 *
 * An absent doc is CREATED rather than skipped: only the planner's live week is
 * auto-seeded, so a forward-shifted apply (and every chat apply, which always
 * targets a week the planner may never have opened) would otherwise land its
 * days while its week summary silently went missing — the FEAT-112 follow-up.
 */
async function upsertWeekPlan(input: ApplyWeekPlanInput): Promise<void> {
  const { familyId, childId, weekStart, children, readAloudBookId } = input
  const weekRef = doc(weeksCollection(familyId), weekStart)
  const weekSnap = await getDoc(weekRef)
  const planGoals = planGoalsForDraft(input.draft)

  if (!weekSnap.exists()) {
    await setDoc(
      weekRef,
      buildShiftedWeekPlan(
        weekStart,
        children,
        childId,
        planGoals,
        readAloudBookId ?? undefined,
      ),
    )
    return
  }

  const existing = weekSnap.data()
  const existingGoals = existing.childGoals ?? []
  const childGoalIndex = existingGoals.findIndex(
    (g: { childId: string }) => g.childId === childId,
  )
  const updatedGoals = [...existingGoals]
  if (childGoalIndex >= 0) {
    updatedGoals[childGoalIndex] = {
      ...updatedGoals[childGoalIndex],
      goals: [...updatedGoals[childGoalIndex].goals, ...planGoals],
    }
  } else {
    updatedGoals.push({ childId, goals: planGoals })
  }

  // `undefined` means "don't touch the book" (the chat); a string sets it and
  // `null` clears it (the planner's picker). Only the two explicit cases strip
  // the existing field, so a chat apply can never blank a book the parent chose.
  if (readAloudBookId === undefined) {
    await setDoc(weekRef, { ...existing, childGoals: updatedGoals })
    return
  }
  const { readAloudBookId: _existing, ...withoutBook } = existing
  void _existing
  await setDoc(weekRef, {
    ...withoutBook,
    childGoals: updatedGoals,
    ...(readAloudBookId ? { readAloudBookId } : {}),
  })
}

/**
 * Write a draft weekly plan to its `WeekPlan` doc and its Mon–Fri day logs.
 *
 * **The single Apply.** Every day write routes through `setDayLogGuarded`, so
 * the FEAT-114 preservation guard refuses any transition that would drop a
 * completed row, its evidence, or a block carrying logged minutes — on this path
 * exactly as on a tap in Today.
 *
 * Throws {@link WeekApplyError} if a write fails, carrying the days that DID
 * land so the caller can say so instead of implying nothing happened.
 */
export async function applyDraftWeek(
  input: ApplyWeekPlanInput,
): Promise<ApplyWeekPlanResult> {
  const {
    familyId,
    childId,
    weekStart,
    draft,
    activityConfigs,
    lessonCardMap = new Map<string, string>(),
    canEdit,
  } = input

  if (!canEdit) {
    throw new WeekApplyError(
      'Applying a week is a parent action.',
      { daysWritten: [], weekPlanWritten: false },
    )
  }

  const result: ApplyWeekPlanResult = { daysWritten: [], weekPlanWritten: false }

  try {
    await upsertWeekPlan(input)
    result.weekPlanWritten = true

    for (const dayPlan of applicableDays(draft)) {
      const dayItems = dayPlan.items.filter((item) => item.accepted)
      const dateKey = dateKeyForDayPlan(weekStart, dayPlan.day as WeekDay)
      const dayLogRef = doc(daysCollection(familyId), dayLogDocId(dateKey, childId))
      const dayLogSnap = await getDoc(dayLogRef)

      const checklist = buildApplyChecklist(dayItems, activityConfigs, lessonCardMap)
      const blocks = buildApplyBlocks(dayItems)
      const dailyBudgetMinutes = Math.round(dayPlan.timeBudgetMinutes)
      const now = new Date().toISOString()

      if (dayLogSnap.exists()) {
        await setDayLogGuarded(
          dayLogRef,
          buildAppliedDayLog(dayLogSnap.data(), checklist, blocks, dailyBudgetMinutes, now),
          'apply-plan',
        )
      } else {
        await setDayLogGuarded(
          dayLogRef,
          {
            childId,
            date: dateKey,
            blocks,
            checklist,
            dailyBudgetMinutes,
            createdAt: now,
            updatedAt: now,
          },
          'apply-plan-new',
        )
      }
      result.daysWritten.push(dateKey)
    }
  } catch (err) {
    throw new WeekApplyError(
      err instanceof Error ? err.message : 'Failed to apply plan.',
      result,
      { cause: err },
    )
  }

  return result
}
